In [14]:
import pandas as pd
import numpy as np

In [3]:
# Load in movie_data and book_data pickle files
movie_df = pd.read_pickle('../dump/movie_data')
book_df = pd.read_pickle('../dump/book_data')

In [69]:
first_merge = pd.merge(movie_df,book_df,left_on="movie_title",right_on="book_title",how='left')

In [80]:
first_merge

,movie_title,rating,vote,certificate,genre,release_date,metascore,keywords,budget,opening_weekend_usa,...,distributor,language,country,book_title,author,rating_value,rating_count,review_count,page,year
0,After We Collided,5.0,16193,R,"[Drama, Romance]",2020-10-23,NaN,"[sequel, birthday, boyfriend girlfriend sex, b...",NaN,422899.0,...,CalMaple,"[English, Chinese]",[USA],NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,The Godfather,9.2,1613156,R,"[Crime, Drama]",1972-03-24,100.0,"[crime family, mafia, patriarch, organized cri...",6000000.0,302393.0,...,ParamountPictures,"[English, Italian, Latin]",[USA],The Godfather,Mario Puzo,4.36,343457.0,8930.0,448.0,1969.0
2,Harry Potter and the Sorcerer's Stone,7.6,654081,PG,"[Adventure, Family, Fantasy]",2001-11-16,64.0,"[magic, wizard, school of magic, based on nove...",125000000.0,90294621.0,...,WarnerBros.,[English],"[UK, USA]",Harry Potter and the Sorcerer's Stone,J.K. Rowling,4.48,7292896.0,115556.0,309.0,1997.0
3,Unknown,6.8,248401,PG-13,"[Action, Thriller]",2011-02-18,NaN,"[amnesia, coma, airport, scientist, nurse]",30000000.0,21856389.0,...,DarkCastleEntertainment,"[English, German, Turkish, Arabic]","[UK, Germany, France, USA]",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,The Lord of the Rings: The Fellowship of the Ring,8.8,1655208,PG-13,"[Action, Adventure, Drama]",2001-12-19,92.0,"[ring, quest, hobbit, epic, elf]",93000000.0,47211490.0,...,NewLineCinema,"[English, Sindarin]","[NewZealand, USA]",NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1998,V.I. Warshawski,5.0,4710,R,"[Action, Comedy, Crime]",1991-07-26,NaN,"[female stockinged feet, pantyhose, camera sho...",NaN,3603338.0,...,HollywoodPictures,[English],[USA],NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999,Anne of Green Gables,7.0,1113,Passed,"[Comedy, Drama, Family]",1934-11-23,NaN,"[character name as title, anne of green gables...",226000.0,NaN,...,RKORadioPictures,[English],[USA],Anne of Green Gables,L.M. Montgomery,4.26,750685.0,23957.0,320.0,1908.0
2000,Odds Against Tomorrow,7.4,3780,Approved,"[Crime, Drama, Thriller]",1959-11-01,NaN,"[new york city, heist, bank robbery, caper, ne...",NaN,NaN,...,HarBelProductions,[English],[USA],NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001,Once Is Not Enough,4.6,629,R,"[Drama, Romance]",1975-06-20,NaN,"[older man younger woman relationship, age dif...",NaN,NaN,...,AriesProductions,[English],[USA],NaN,NaN,NaN,NaN,NaN,NaN,NaN
2002,Unidentified Flying Oddball,5.3,992,G,"[Comedy, Family, Adventure]",1979-07-26,66.0,"[time travel, time travel into the past, refer...",NaN,NaN,...,WaltDisneyProductions,[English],[USA],NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [71]:
first_merge[first_merge.movie_title == 'Little Women']

,movie_title,rating,vote,certificate,genre,release_date,metascore,keywords,budget,opening_weekend_usa,...,distributor,language,country,book_title,author,rating_value,rating_count,review_count,page,year
6,Little Women,7.8,140641,PG,"[Drama, Romance]",2019-12-25,91.0,"[aspiring writer, poverty, women's rights, dea...",40000000.0,16755310.0,...,ColumbiaPictures,"[English, French]",[USA],Little Women,Louisa May Alcott,4.09,1717984.0,31224.0,449.0,1868.0
195,Little Women,7.3,52122,PG,"[Drama, Family, Romance]",1994-12-25,87.0,"[american civil war, f rated, female protagoni...",18000000.0,2411247.0,...,ColumbiaPictures,"[English, German, French]","[USA, Canada]",Little Women,Louisa May Alcott,4.09,1717984.0,31224.0,449.0,1868.0
887,Little Women,7.3,6677,Approved,"[Drama, Family, Romance]",1949-04-01,61.0,"[tomboy, writing, color remake of black and wh...",NaN,NaN,...,Metro-Goldwyn-Mayer(MGM),"[English, German]",[USA],Little Women,Louisa May Alcott,4.09,1717984.0,31224.0,449.0,1868.0
1230,Little Women,7.2,6419,Passed,"[Drama, Family, Romance]",1933-11-24,92.0,"[coming of age, strong female lead, strong fem...",424000.0,NaN,...,RKORadioPictures,"[English, German]",[USA],Little Women,Louisa May Alcott,4.09,1717984.0,31224.0,449.0,1868.0

In [72]:
first_merge.book_title.isna().sum()

1421

In [73]:
2000-1421

579

In [81]:
first_merge_inner = pd.merge(movie_df,book_df,left_on="movie_title",right_on="book_title",how='inner')

In [82]:
first_merge_inner

,movie_title,rating,vote,certificate,genre,release_date,metascore,keywords,budget,opening_weekend_usa,...,distributor,language,country,book_title,author,rating_value,rating_count,review_count,page,year
0,The Godfather,9.2,1613156,R,"[Crime, Drama]",1972-03-24,100.0,"[crime family, mafia, patriarch, organized cri...",6000000.0,302393.0,...,ParamountPictures,"[English, Italian, Latin]",[USA],The Godfather,Mario Puzo,4.36,343457,8930,448.0,1969.0
1,Harry Potter and the Sorcerer's Stone,7.6,654081,PG,"[Adventure, Family, Fantasy]",2001-11-16,64.0,"[magic, wizard, school of magic, based on nove...",125000000.0,90294621.0,...,WarnerBros.,[English],"[UK, USA]",Harry Potter and the Sorcerer's Stone,J.K. Rowling,4.48,7292896,115556,309.0,1997.0
2,Little Women,7.8,140641,PG,"[Drama, Romance]",2019-12-25,91.0,"[aspiring writer, poverty, women's rights, dea...",40000000.0,16755310.0,...,ColumbiaPictures,"[English, French]",[USA],Little Women,Louisa May Alcott,4.09,1717984,31224,449.0,1868.0
3,Little Women,7.3,52122,PG,"[Drama, Family, Romance]",1994-12-25,87.0,"[american civil war, f rated, female protagoni...",18000000.0,2411247.0,...,ColumbiaPictures,"[English, German, French]","[USA, Canada]",Little Women,Louisa May Alcott,4.09,1717984,31224,449.0,1868.0
4,Little Women,7.3,6677,Approved,"[Drama, Family, Romance]",1949-04-01,61.0,"[tomboy, writing, color remake of black and wh...",NaN,NaN,...,Metro-Goldwyn-Mayer(MGM),"[English, German]",[USA],Little Women,Louisa May Alcott,4.09,1717984,31224,449.0,1868.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,Losing Isaiah,6.5,5478,R,[Drama],1995-03-17,NaN,"[baby, custody battle, social worker, cartoon ...",17000000.0,2520972.0,...,ParamountPictures,[English],[USA],Losing Isaiah,Seth Margolis,3.86,147,15,374.0,1993.0
578,The Heart Is a Lonely Hunter,7.6,3554,G,[Drama],1968-07-31,NaN,"[doctor, african american, drifter, loneliness...",2000000.0,NaN,...,WarnerBros./SevenArts,"[English, AmericanSignLanguage]",[USA],The Heart Is a Lonely Hunter,Carson McCullers,3.98,94002,6511,359.0,1940.0
579,Island of the Blue Dolphins,6.1,416,1h,"[Adventure, Biography, Drama]",1964-09-10,NaN,"[girl and her dog, death of pet, island, dog t...",NaN,NaN,...,RobertB.RadnitzProductions,[English],[USA],Island of the Blue Dolphins,Scott O'Dell,3.84,298468,8488,184.0,1960.0
580,From the Terrace,6.7,2438,Passed,"[Drama, Romance]",1960-09-09,NaN,"[mother son relationship, wilmington delaware,...",NaN,NaN,...,Linebrook,[English],[USA],From the Terrace,John O'Hara,3.92,409,33,981.0,1958.0
581,Anne of Green Gables,7.0,1113,Passed,"[Comedy, Drama, Family]",1934-11-23,NaN,"[character name as title, anne of green gables...",226000.0,NaN,...,RKORadioPictures,[English],[USA],Anne of Green Gables,L.M. Montgomery,4.26,750685,23957,320.0,1908.0

In [74]:
# Find movies without a matching book
need_book = test_merge[first_merge.book_title.isna() == True]
need_book_list = list(need_book.movie_title)
len(need_book_list)

1421

In [75]:
need_book

,movie_title,rating,vote,certificate,genre,release_date,metascore,keywords,budget,opening_weekend_usa,...,distributor,language,country,book_title,author,rating_value,rating_count,review_count,page,year
0,After We Collided,5.0,16193,R,"[Drama, Romance]",2020-10-23,NaN,"[sequel, birthday, boyfriend girlfriend sex, b...",NaN,422899.0,...,CalMaple,"[English, Chinese]",[USA],NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Unknown,6.8,248401,PG-13,"[Action, Thriller]",2011-02-18,NaN,"[amnesia, coma, airport, scientist, nurse]",30000000.0,21856389.0,...,DarkCastleEntertainment,"[English, German, Turkish, Arabic]","[UK, Germany, France, USA]",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,The Lord of the Rings: The Fellowship of the Ring,8.8,1655208,PG-13,"[Action, Adventure, Drama]",2001-12-19,92.0,"[ring, quest, hobbit, epic, elf]",93000000.0,47211490.0,...,NewLineCinema,"[English, Sindarin]","[NewZealand, USA]",NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,The Beastmaster,6.2,20713,PG,"[Action, Adventure, Fantasy]",1982-08-20,NaN,"[sword and sorcery, breasts, animal human comm...",8000000.0,2955641.0,...,LeisureInvestmentCompany,[English],"[USA, WestGermany]",NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Goodfellas,8.7,1016280,R,"[Biography, Crime, Drama]",1990-09-21,90.0,"[gangster, organized crime, sadistic psychopat...",25000000.0,6368901.0,...,WarnerBros.,"[English, Italian]",[USA],NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1996,The Wayward Bus,6.7,455,Not,[Drama],1957-05-27,NaN,"[psychotronic film, bus, cafe, roadtrip, road ...",NaN,NaN,...,TwentiethCenturyFox,[English],[USA],NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998,V.I. Warshawski,5.0,4710,R,"[Action, Comedy, Crime]",1991-07-26,NaN,"[female stockinged feet, pantyhose, camera sho...",NaN,3603338.0,...,HollywoodPictures,[English],[USA],NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000,Odds Against Tomorrow,7.4,3780,Approved,"[Crime, Drama, Thriller]",1959-11-01,NaN,"[new york city, heist, bank robbery, caper, ne...",NaN,NaN,...,HarBelProductions,[English],[USA],NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001,Once Is Not Enough,4.6,629,R,"[Drama, Romance]",1975-06-20,NaN,"[older man younger woman relationship, age dif...",NaN,NaN,...,AriesProductions,[English],[USA],NaN,NaN,NaN,NaN,NaN,NaN,NaN
2002,Unidentified Flying Oddball,5.3,992,G,"[Comedy, Family, Adventure]",1979-07-26,66.0,"[time travel, time travel into the past, refer...",NaN,NaN,...,WaltDisneyProductions,[English],[USA],NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
# Test set.difference
movie_title_list = list(movie_df.movie_title)
book_title_list = list(book_df.book_title)
need_book_pre = list(set(movie_title_list).difference(set(book_title_list)))
need_book = [book.replace('&','and').replace(":",'') for book in need_book_pre]
len(need_book)

1397

In [31]:
# Load in found_book_data pickle files
found_book_df = pd.read_pickle('../dump/found_book')

In [43]:
found_book_df[found_book_df.book_title == "Little Women"]

Empty DataFrame
Columns: [book_title, author, rating_value, rating_count, review_count, page, year]
Index: []

In [87]:
# Combine book_df and found_book_df
book_all_df = pd.concat([book_df,found_book_df])

In [88]:
book_all_df

,book_title,author,rating_value,rating_count,review_count,page,year
0,Harry Potter and the Sorcerer's Stone,J.K. Rowling,4.48,7292896.0,115556.0,309.0,1997.0
1,Harry Potter and the Chamber of Secrets,J.K. Rowling,4.43,2821010.0,54542.0,341.0,1998.0
2,Harry Potter and the Prisoner of Azkaban,J.K. Rowling,4.57,2908354.0,57262.0,435.0,1999.0
3,Harry Potter and the Goblet of Fire,J.K. Rowling,4.56,2676621.0,47961.0,734.0,2000.0
4,Harry Potter and the Order of the Phoenix,J.K. Rowling,4.50,2585450.0,43737.0,870.0,2003.0
...,...,...,...,...,...,...,...
1392,The Hanging Tree - Sheet Music: (from The Hung...,Hal Leonard Corporation,4.14,7.0,2.0,NaN,2015.0
1393,Fifty Shades Darker,E.L. James,3.84,761148.0,29215.0,532.0,2011.0
1394,Bless the Child,Cathy Cash Spellman,3.80,607.0,54.0,608.0,1993.0
1395,Playing for Keeps,R.L. Mathewson,4.05,106251.0,5587.0,330.0,2011.0
1396,The Badlanders,Jack Slade,3.25,4.0,0.0,NaN,1973.0

In [89]:
# Merge movie_df and book_all_df
combined_df = pd.merge(movie_df, book_all_df, left_on='movie_title',right_on='book_title',how='inner')

In [90]:
combined_df

,movie_title,rating,vote,certificate,genre,release_date,metascore,keywords,budget,opening_weekend_usa,...,distributor,language,country,book_title,author,rating_value,rating_count,review_count,page,year
0,After We Collided,5.0,16193,R,"[Drama, Romance]",2020-10-23,NaN,"[sequel, birthday, boyfriend girlfriend sex, b...",NaN,422899.0,...,CalMaple,"[English, Chinese]",[USA],After We Collided,Anna Todd,3.78,92534.0,5490.0,674.0,2013.0
1,The Godfather,9.2,1613156,R,"[Crime, Drama]",1972-03-24,100.0,"[crime family, mafia, patriarch, organized cri...",6000000.0,302393.0,...,ParamountPictures,"[English, Italian, Latin]",[USA],The Godfather,Mario Puzo,4.36,343457.0,8930.0,448.0,1969.0
2,Harry Potter and the Sorcerer's Stone,7.6,654081,PG,"[Adventure, Family, Fantasy]",2001-11-16,64.0,"[magic, wizard, school of magic, based on nove...",125000000.0,90294621.0,...,WarnerBros.,[English],"[UK, USA]",Harry Potter and the Sorcerer's Stone,J.K. Rowling,4.48,7292896.0,115556.0,309.0,1997.0
3,Harry Potter and the Sorcerer's Stone,7.6,654081,PG,"[Adventure, Family, Fantasy]",2001-11-16,64.0,"[magic, wizard, school of magic, based on nove...",125000000.0,90294621.0,...,WarnerBros.,[English],"[UK, USA]",Harry Potter and the Sorcerer's Stone,J.K. Rowling,4.48,7297366.0,115643.0,309.0,1997.0
4,Little Women,7.8,140641,PG,"[Drama, Romance]",2019-12-25,91.0,"[aspiring writer, poverty, women's rights, dea...",40000000.0,16755310.0,...,ColumbiaPictures,"[English, French]",[USA],Little Women,Louisa May Alcott,4.09,1717984.0,31224.0,449.0,1868.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1237,From the Terrace,6.7,2438,Passed,"[Drama, Romance]",1960-09-09,NaN,"[mother son relationship, wilmington delaware,...",NaN,NaN,...,Linebrook,[English],[USA],From the Terrace,John O'Hara,3.92,409.0,33.0,981.0,1958.0
1238,Anne of Green Gables,7.0,1113,Passed,"[Comedy, Drama, Family]",1934-11-23,NaN,"[character name as title, anne of green gables...",226000.0,NaN,...,RKORadioPictures,[English],[USA],Anne of Green Gables,L.M. Montgomery,4.26,750685.0,23957.0,320.0,1908.0
1239,Odds Against Tomorrow,7.4,3780,Approved,"[Crime, Drama, Thriller]",1959-11-01,NaN,"[new york city, heist, bank robbery, caper, ne...",NaN,NaN,...,HarBelProductions,[English],[USA],Odds Against Tomorrow,Nathaniel Rich,3.39,2242.0,307.0,304.0,2013.0
1240,Once Is Not Enough,4.6,629,R,"[Drama, Romance]",1975-06-20,NaN,"[older man younger woman relationship, age dif...",NaN,NaN,...,AriesProductions,[English],[USA],Once Is Not Enough,Jacqueline Susann,3.72,7769.0,184.0,467.0,1973.0
1241,Unidentified Flying Oddball,5.3,992,G,"[Comedy, Family, Adventure]",1979-07-26,66.0,"[time travel, time travel into the past, refer...",NaN,NaN,...,WaltDisneyProductions,[English],[USA],Unidentified Flying Oddball,Vic Crume,2.74,19.0,3.0,NaN,1979.0

In [91]:
final_book_list = list(combined_df.book_title)

In [92]:
final_author_list = list(combined_df.author)

In [94]:
len(final_book_list)

1242

### Practice on fuzzywuzzy package

In [9]:
from fuzzywuzzy import fuzz
from fuzzywuzzy import process
Str1 = "Los Angeles Lakers"
Str2 = "Lakers"
Ratio = fuzz.ratio(Str1.lower(),Str2.lower())
Partial_Ratio = fuzz.partial_ratio(Str1.lower(),Str2.lower())
print(Ratio)
print(Partial_Ratio)

50
100

In [21]:
movie_title_list_s=['After We Collided',
 'The Godfather',
 "Harry Potter and the Sorcerer's Stone",
 'Unknown',
 'The Lord of the Rings: The Fellowship of the Ring',
 'The Beastmaster',
 'Little Women']

In [22]:
book_title_list_s = ['The Running Man',
 'Left Behind',"Harry Potter and the Sorcerer's Stone",
 'Harry Potter and the Chamber of Secrets',
 'Harry Potter and the Prisoner of Azkaban',
 'Harry Potter and the Goblet of Fire',
 'Harry Potter and the Order of the Phoenix',
 'Twilight']

In [23]:
movie_title_list_s[4]
Ratios = process.extract(movie_title_list_s[4],book_title_list_s)
match = process.extractOne(movie_title_list_s[4],book_title_list_s)
if match[1] > 90:
    print(match[0])
else:
    print('no match')

no match

In [27]:
match=[]
for movie in movie_title_list:
    potential = process.extractOne(movie,book_title_list)
    if potential[1] > 90:
        match.append(potential[0])
    else:
        match.append(np.nan)

In [30]:
c = 0
for x in match:
    if x is np.nan:
        c += 1
c

1367

In [29]:
1800-c

433