In [14]:
import pandas as pd
import numpy as np

In [3]:
# Load in movie_data and book_data picke files
movie_df = pd.read_pickle('../dump/movie_data')
book_df = pd.read_pickle('../dump/book_data')

In [4]:
test_merge = pd.merge(movie_df,book_df,left_on="movie_title",right_on="book_title",how='left')

In [5]:
test_merge

,movie_title,rating,vote,certificate,genre,release_date,metascore,keywords,budget,opening_weekend_usa,...,distributor,language,country,book_title,author,rating_value,rating_count,review_count,page,year
0,After We Collided,5.0,16193,R,"[Drama, Romance]",2020-10-23,NaN,"[sequel, birthday, boyfriend girlfriend sex, b...",NaN,422899.0,...,CalMaple,"[English, Chinese]",[USA],NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,The Godfather,9.2,1613156,R,"[Crime, Drama]",1972-03-24,100.0,"[crime family, mafia, patriarch, organized cri...",6000000.0,302393.0,...,ParamountPictures,"[English, Italian, Latin]",[USA],The Godfather,Mario Puzo,4.36,343457.0,8930.0,448.0,1969.0
2,Harry Potter and the Sorcerer's Stone,7.6,654081,PG,"[Adventure, Family, Fantasy]",2001-11-16,64.0,"[magic, wizard, school of magic, based on nove...",125000000.0,90294621.0,...,WarnerBros.,[English],"[UK, USA]",Harry Potter and the Sorcerer's Stone,J.K. Rowling,4.48,7292896.0,115556.0,309.0,1997.0
3,Unknown,6.8,248401,PG-13,"[Action, Thriller]",2011-02-18,NaN,"[amnesia, coma, airport, scientist, nurse]",30000000.0,21856389.0,...,DarkCastleEntertainment,"[English, German, Turkish, Arabic]","[UK, Germany, France, USA]",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,The Lord of the Rings: The Fellowship of the Ring,8.8,1655208,PG-13,"[Action, Adventure, Drama]",2001-12-19,92.0,"[ring, quest, hobbit, epic, elf]",93000000.0,47211490.0,...,NewLineCinema,"[English, Sindarin]","[NewZealand, USA]",NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1998,V.I. Warshawski,5.0,4710,R,"[Action, Comedy, Crime]",1991-07-26,NaN,"[female stockinged feet, pantyhose, camera sho...",NaN,3603338.0,...,HollywoodPictures,[English],[USA],NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999,Anne of Green Gables,7.0,1113,Passed,"[Comedy, Drama, Family]",1934-11-23,NaN,"[character name as title, anne of green gables...",226000.0,NaN,...,RKORadioPictures,[English],[USA],Anne of Green Gables,L.M. Montgomery,4.26,750685.0,23957.0,320.0,1908.0
2000,Odds Against Tomorrow,7.4,3780,Approved,"[Crime, Drama, Thriller]",1959-11-01,NaN,"[new york city, heist, bank robbery, caper, ne...",NaN,NaN,...,HarBelProductions,[English],[USA],NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001,Once Is Not Enough,4.6,629,R,"[Drama, Romance]",1975-06-20,NaN,"[older man younger woman relationship, age dif...",NaN,NaN,...,AriesProductions,[English],[USA],NaN,NaN,NaN,NaN,NaN,NaN,NaN
2002,Unidentified Flying Oddball,5.3,992,G,"[Comedy, Family, Adventure]",1979-07-26,66.0,"[time travel, time travel into the past, refer...",NaN,NaN,...,WaltDisneyProductions,[English],[USA],NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# Find movies without a matching book
need_book = test_merge[test_merge.book_title.isna() == True]
need_book_list = list(need_book.movie_title)
len(need_book_list)

1421

In [24]:
# Test set.difference
movie_title_list = list(movie_df.movie_title)
book_title_list = list(book_df.book_title)
need_book_pre = list(set(movie_title_list).difference(set(book_title_list)))
need_book = [book.replace('&','and').replace(":",'') for book in need_book_pre]
len(need_book)

1397

### Practice on fuzzywuzzy package

In [9]:
from fuzzywuzzy import fuzz
from fuzzywuzzy import process
Str1 = "Los Angeles Lakers"
Str2 = "Lakers"
Ratio = fuzz.ratio(Str1.lower(),Str2.lower())
Partial_Ratio = fuzz.partial_ratio(Str1.lower(),Str2.lower())
print(Ratio)
print(Partial_Ratio)

50
100

In [21]:
movie_title_list_s=['After We Collided',
 'The Godfather',
 "Harry Potter and the Sorcerer's Stone",
 'Unknown',
 'The Lord of the Rings: The Fellowship of the Ring',
 'The Beastmaster',
 'Little Women']

In [22]:
book_title_list_s = ['The Running Man',
 'Left Behind',"Harry Potter and the Sorcerer's Stone",
 'Harry Potter and the Chamber of Secrets',
 'Harry Potter and the Prisoner of Azkaban',
 'Harry Potter and the Goblet of Fire',
 'Harry Potter and the Order of the Phoenix',
 'Twilight']

In [23]:
movie_title_list_s[4]
Ratios = process.extract(movie_title_list_s[4],book_title_list_s)
match = process.extractOne(movie_title_list_s[4],book_title_list_s)
if match[1] > 90:
    print(match[0])
else:
    print('no match')

no match

In [27]:
match=[]
for movie in movie_title_list:
    potential = process.extractOne(movie,book_title_list)
    if potential[1] > 90:
        match.append(potential[0])
    else:
        match.append(np.nan)

In [30]:
c = 0
for x in match:
    if x is np.nan:
        c += 1
c

1367

In [29]:
1800-c

433